sudo: false
os:
- linux
language: node_js
node_js:
- 8
env:
  global:
    secure: Zwczjwc2gqz/Xd8dkWyojrdK0nYVKk4SQbvNQ/aznQVGXJNy8vTok+NiNzIsIYKgdkWsZHtauNzxW8G+M8JFAjOURHQOKMlC1xIqlHMt0O7q93FdGSSkIsjQuSZKH6XjUI37bmS4rrBZUAilOKj8l+W1hdcKyVLJohwtL0FABY4RumVC5ry9BeAjZJyEATKtlvx5HnR04CHevp+PS5mTQ6gc8bafZ4YQXis2gpgLPP+r+lkqq6BedzU3IV4Itd8FFdZew88R+S2Y9q2mln95YxJ02jMguW9ZEOXz8m9PbYn3VWdmsZ3k+0PzwNUmferSQ9ryCmMecLYX7GFCwOvqYAWPKbPfP9o/rO1h6g+U/SsAsKvY/sGlmIOL0P3f8DURgDsSqFMBhqVcvinZapU4/+V6qSOu5HCyRuqokFKPnDirCwKwSguVGWVYuLRbT2BsoVjavyAz5QQb9teym6W/t2nirQM7Wm7pyAQglbLE25v6SyYyYYit7OtZ5i6YfsP/YNixC0RrLS2ZDlox5rktj3eUNF56jn3WN/PIY+T5Nww1KIhqcTUos6nVmDrqSweSe96lmzVJnYUP09LLSBGFjoqYQ6osnh0olhs6Ggjd8EuG9wGkSq9cFdpOcr9dwxYDCbMUckSEk6Ha/jw+fE2Li05p6STkf7F56eA3J0YOgCs=
before_script:
- npm install -g vsce;
script:
- vsce package;
deploy:
- provider: releases
  api_key:
    secure: q5Lid5FevBT9DUSTbjENbuYXYTOn+R2xA9F3n510ifh9OD9HilQfufvkrdlYAQnonlKKQ2MqCkQXP1w4ZvkeiGsMhcfejU0XP9iwXLe+opAvAAat/o8XajMP8P/n7laNDQJjNKqOWfnVHje9WmS8hNn5v81MjmJkGaPE7Rcg1VFJrkN1Raxd8XMPhhGukTd6PUOk75eJOqdEYtyngzBtowYYcrpT5BcDinpjMArpOouC1B4JhLaKcWtjjsnYBHzOR82p0tCxrjeuw+NmIzZKvNUTHwPuFG00qWRzmwUucEpRDI3Eb1A5G1feUS2BZYf8yVKiTcGQxrab/Kc38lXedFZgibhPtRSHdjyNlvQRylvp+dRysFRtev4+6VvkRZWnbqpPCOEIYtH4aUooH4XpfM8o6Bgl0xTSHOVOQ7TegV1tj2zgPE5/d1OVfvchGzup2kOp7XlrP+tFXXUKHyUKnwbtFbXUNT92OIkD/JDKIArEXdCt492iJpesVbV66p1MP/hFctr+jPn7p/9k0wTB2D/17XfuKW+6gB24luP+BaH8YgpTzpCpeYxZQtk1bSGQeDV/fzCGrXMxRZmd16hmIpEmSepbQ8JlGYBXY5otAGNJVeEXXnAKxBTekbUZm3EvS/Ul5NZxNchwIJ9+FX0pXZ6FTM4XUjQO2vVY1LAedTA=
  file: "*.vsix"
  file_glob: true
  skip_cleanup: true
  on:
    repo: rockinrimmer/VSCode-Liquibase-Snippets
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: rockinrimmer/VSCode-Liquibase-Snippets
    tags: true
    condition: $TRAVIS_OS_NAME = linux