sudo: false
os:
- linux
language: node_js
node_js:
- 8
env:
  global:
    secure: Asp8wR0p43EBSYqe4Quvmmk5rnKqW2yKHKqp9Km2SYHnwnTfOaHO4RqabMvU7KUxFcw8b2Q9YZIA7ibGZHP14rCiPWQKQQzFCknwyWH3+EG68wYjQB29/u5EmT4l7msnj6zp0YAIc6GjcOV6uiZn18MA39zhiIXhFtOOVkOvZjOwOnIeOHBRy/G1GJeJwbisgUggfdXkFEj19bN6J0cqdmhvPXnSao9DcTfGj95jzRVIjj+YHKnMl+mJY61JhBqxxxJ+jpQZr14jeXp8mv4ilZzhY3U34w+FSx/8+bIf4tXY0WCQrtyOFTA6kTajjw6AG/GTiVfv0ZLZXoNTu/7lokulV7Stvgih8wIJOF0RfoKqNtPJjFEQFGrfDBDawzzxnS5wXtgjlc/pejJUWZvp8leQE1n4JBoOCMm/bRTYdo0vltDGBx0UE0EsoFzIdZNv3h8DZ+pe4+SePbIJoLNf8b7TCqRF5blpwb6k/zUn7reb5Am++JvB1twbRbzjisprGqkNadpxPSsy0lOXph9gYoEAvDu1dIL52kKEolrVvQmRCMRdjk5nZgu+SYqOuefaT6K7g9O8A6jBijl58TC8qmAcCrH/1KzQKhsZoQOwj93T9VlfNGgG14XW4OCTT/yTxqG02etgRU5Pio0dTiUJ3k08fDjTO8NqTNGQCQSoux0=
before_script:
- npm install -g vsce;
script:
- vsce package;
deploy:
- provider: releases
  api_key:
    secure: q5Lid5FevBT9DUSTbjENbuYXYTOn+R2xA9F3n510ifh9OD9HilQfufvkrdlYAQnonlKKQ2MqCkQXP1w4ZvkeiGsMhcfejU0XP9iwXLe+opAvAAat/o8XajMP8P/n7laNDQJjNKqOWfnVHje9WmS8hNn5v81MjmJkGaPE7Rcg1VFJrkN1Raxd8XMPhhGukTd6PUOk75eJOqdEYtyngzBtowYYcrpT5BcDinpjMArpOouC1B4JhLaKcWtjjsnYBHzOR82p0tCxrjeuw+NmIzZKvNUTHwPuFG00qWRzmwUucEpRDI3Eb1A5G1feUS2BZYf8yVKiTcGQxrab/Kc38lXedFZgibhPtRSHdjyNlvQRylvp+dRysFRtev4+6VvkRZWnbqpPCOEIYtH4aUooH4XpfM8o6Bgl0xTSHOVOQ7TegV1tj2zgPE5/d1OVfvchGzup2kOp7XlrP+tFXXUKHyUKnwbtFbXUNT92OIkD/JDKIArEXdCt492iJpesVbV66p1MP/hFctr+jPn7p/9k0wTB2D/17XfuKW+6gB24luP+BaH8YgpTzpCpeYxZQtk1bSGQeDV/fzCGrXMxRZmd16hmIpEmSepbQ8JlGYBXY5otAGNJVeEXXnAKxBTekbUZm3EvS/Ul5NZxNchwIJ9+FX0pXZ6FTM4XUjQO2vVY1LAedTA=
  file: "*.vsix"
  file_glob: true
  skip_cleanup: true
  on:
    repo: rockinrimmer/VSCode-Liquibase-Snippets
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: rockinrimmer/VSCode-Liquibase-Snippets
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
